# Generated by Django 4.0.4 on 2022-04-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='company-logo')),
                ('brand_name', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=255)),
                ('promotional_sentence', models.TextField()),
            ],
        ),
    ]
