# Generated by Django 4.0.4 on 2022-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_qrcode_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.FileField(blank=True, upload_to='company-qrcode'),
        ),
    ]
