# Generated by Django 4.0.4 on 2022-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_qrcode_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.BinaryField(default=1),
            preserve_default=False,
        ),
    ]
