# Generated by Django 4.0.4 on 2022-04-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_qrcode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='promotional_sentence',
            field=models.TextField(default=b''),
        ),
    ]
