# Generated by Django 4.0.4 on 2022-04-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_qrcode_promotional_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
