# Generated by Django 4.0.4 on 2022-07-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_qrcode_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
