# Generated by Django 4.0.4 on 2022-07-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_qrcode_end_date_qrcode_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='privacy_policy_check',
            field=models.BooleanField(default=True),
        ),
    ]
