# Generated by Django 4.0.4 on 2022-08-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_qrcode_email_qrcode_name_qrcode_privacy_policy_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
