# Generated by Django 4.0.4 on 2022-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_qrcode_is_end_qrcode_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
