# Generated by Django 4.0.4 on 2022-09-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_qrcode_is_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
