# Generated by Django 4.0.4 on 2023-01-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_qrcode_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='location',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='country',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrcode',
            name='region',
            field=models.TextField(default=b'', max_length=255),
        ),
    ]
