# Generated by Django 4.0.4 on 2023-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_qrcodev2_surveycoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodev2',
            name='service',
            field=models.TextField(max_length=255),
        ),
    ]
