# Generated by Django 4.0.4 on 2023-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_qrcodev2_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodev2',
            name='participantsLimit',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveycoordinator',
            name='participants',
            field=models.TextField(blank=True, null=True),
        ),
    ]
