# Generated by Django 4.0.4 on 2023-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_qrcodev2_participantslimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodev2',
            name='participantsLimit',
            field=models.JSONField(blank=True, decoder=dict, null=True),
        ),
    ]
