# Generated by Django 4.0.4 on 2023-09-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_qrcodev2_participantslimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodev2',
            name='participantsLimit',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
