# Generated by Django 4.0.4 on 2023-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_qrcodev2_participantslimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycoordinator',
            name='participants',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
